site_name: Book of Huawei

# Додайте цю секцію para налаштування плагінів
plugins:
  - search # Вбудований плагін пошуку
  - table-reader # Ваш плагін для читання таблиць з Excel
  - glightbox # Плагін для гарної галереї зображень
  - with-pdf: # Плагін для створення PDF
      cover: true # Вмикає створення обкладинки
      cover_title: "Назва вашого посібника" # Ваша назва
      cover_subtitle: "Технічна документація" # Ваш підзаголовок
      cover_logo: "assets/cover.png" # Шлях до вашої обкладинки
      output_path: "docs/document.pdf" # Куди зберегти PDF

# Секція для додаткових стилів (знадобиться для налаштування обкладинки на сайті)
extra_css:
  - stylesheets/extra.css
